#!/bin/bash
echo "Top 5 IP addresses with the most requests:"
awk '{print $1}' nginx-access.log | sort | uniq -c | sort -nr | awk '{print $2, " - " $1 " requests" }' | head -n 5
echo

echo "Top 5 most requested paths:"
awk '{print $7}' nginx-access.log | sort | uniq -c | sort -nr | awk '{print $2 " - " $1 " request" }'| head -n 5
echo

echo "Top 5 response status codes:"
awk '$9 ~ /^[0-9]+$/ {print $9}' nginx-access.log | sort | uniq -c | sort -nr | awk '{print $2 " - " $1 " request" }' | head -n 5




